### ISSUE TITLE
Problemas ejercicio 5

### ISSUE THREAD

**Issue by Patriesc** [Patriesc/LosBucles#1]
03b3697681b151dd7caddd7482e349957030aad1
Es necesario revisar el ejercicio 5, pues si bien la ejecución es correcta, se podría mejorar.

**Comment by Patriesc** [comment]
Lo he actualizado y ahora no da tantos problemas, igualmente pruébalo por si deberíamos mejorar algo

**Comment by chiarab22** [comment]
**Antes:**
 public void ahoraYo(Scanner teclado) {
        System.out.println("Elija un número del 1 al 100, luego presione cualquier tecla. ");
        teclado.nextLine();
        teclado.nextLine();
        pcRandom = random.nextInt(100) + 1;
        eleccionPc = pcRandom;
        listaNums.add(eleccionPc);
**Despues:**
 public void ahoraYo(Scanner teclado) {
        System.out.println("Elija un número del 1 al 100, luego presione cualquier tecla. ");
        teclado.nextLine();
        pcRandom = random.nextInt(100) + 1;
        eleccionPc = pcRandom;
        listaNums.add(eleccionPc);
